arch: amd64
os: linux
dist: focal

language: node_js
node_js:
  - node

services:
  - docker

before_script:
  - npm run test_env:start

after_script:
  - npm run test_env:stop

after_success:
  - npm run publish_coverage
