services:
  web-client:
    image: selenium/standalone-firefox:4.24.0-20240830 # https://github.com/SeleniumHQ/docker-selenium to get the latest version
    shm_size: '2gb'
    ports:
      - 4444:4444 # http://localhost:4444/ (driver)
      - 7900:7900 # http://localhost:7900/?autoconnect=1&password=secret (VNC)
    volumes:
      - type: bind
        source: ..
        target: /app
        read_only: true
