name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - run: npm ci
      - run: npm run build
      - run: docker compose -f scripts/docker-compose.yml up -d
      - run: npm test --ignore-scripts
      - run: docker compose -f scripts/docker-compose.yml down
        if: ${{ always() }}
      - name: Publish coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './build/coverage/lcov.info'
