name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - run: npm ci
      - run: npm run build
      - run: docker compose -f scripts/docker-compose.yml up -d
      - run: npm test --ignore-scripts
      - run: docker compose -f scripts/docker-compose.yml down
        if: ${{ always() }}
      - run: npm publish
      - name: Deploy documentation
        run: node scripts/deploy.js
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
